swagger: '2.0'
info:
  version: '0.0.0'
  title: Service Component
  description: 'This is the API definition which describes how the care platform will expect your service component to behave'
host: localhost:10010
basePath: /serviceComponent/v0
schemes:
- http
#s
consumes:
- application/json
produces:
- application/json

paths:
  /events:
    x-swagger-router-controller: events
    post:
      description: The platfrom will post new events to this method
      summary: Post new event to service component
      operationId: postEvent
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        description: New event details
        schema:
          $ref: '#/definitions/KeyWithEvent'
      responses:
        200:
          description: Successfully recieved
        400:
          description: Error occoured or you cannot accept the data.

definitions:
#defintions for clients and users
  DeviceInstance:
    type: object
    title: Device Instance
    properties:
      type:
        type: string
        example: Pill Box
      properties:
        type: string
        example: "{\"location\": \"Kitchen\"}"
    required:
    - type
    - properties

  Event:
    title: Event Description
    type: object
    required:
    - type
    - deviceInstance
    - details
    - component
    - date
    properties:
      component:
        type: string
        example: 'Pill Box Component'
      date:
        type: string
        example: '2018-02-27T18:42:29.000Z'
      type:
        type: string
        example: 'Opened'
      details:
        type: string
        example: 'The pill box was opened'
      deviceInstance:
        $ref: '#/definitions/DeviceInstance'

  KeyWithEvent:
    title: Key with Event
    type: object
    required:
    - key
    - event
    properties:
      key:
        type: string
        example: pJN2GqumRbOmtNuCgKlhxjDgRWepazFGuCiikGcizc3GtUM9d8MXz5LCfEI0DjS0HzeiWODd9VGCjcTenttVnsCxG4RH1Sj1QMHe
      event:
        $ref: '#/definitions/Event'